### ISSUE TITLE
Doesn't work out of the box on Ruby 3

### ISSUE THREAD

**Issue by vassilit** [asciidoctor/kramdown-asciidoc#84]
When trying kramdoc after `gem install kramdown-asciidoc`, I've got the following error:

```
<internal:/usr/lib/ruby/3.0.0/rubygems/core_ext/kernel_require.rb>:85:in `require': cannot load such file -- rexml/parsers/baseparser (LoadError)
	from <internal:/usr/lib/ruby/3.0.0/rubygems/core_ext/kernel_require.rb>:85:in `require'
	from /home/vt/.local/share/gem/ruby/3.0.0/gems/kramdown-1.17.0/lib/kramdown/parser/html.rb:10:in `<top (required)>'
	from <internal:/usr/lib/ruby/3.0.0/rubygems/core_ext/kernel_require.rb>:85:in `require'
	from <internal:/usr/lib/ruby/3.0.0/rubygems/core_ext/kernel_require.rb>:85:in `require'
	from /home/vt/.local/share/gem/ruby/3.0.0/gems/kramdown-asciidoc-1.0.1/lib/kramdown-asciidoc/kramdown_ext/parser/html.rb:1:in `<top (required)>'
	from /home/vt/.local/share/gem/ruby/3.0.0/gems/kramdown-asciidoc-1.0.1/lib/kramdown-asciidoc.rb:3:in `require_relative'
	from /home/vt/.local/share/gem/ruby/3.0.0/gems/kramdown-asciidoc-1.0.1/lib/kramdown-asciidoc.rb:3:in `<top (required)>'
	from <internal:/usr/lib/ruby/3.0.0/rubygems/core_ext/kernel_require.rb>:85:in `require'
	from <internal:/usr/lib/ruby/3.0.0/rubygems/core_ext/kernel_require.rb>:85:in `require'
	from /home/vt/.local/share/gem/ruby/3.0.0/gems/kramdown-asciidoc-1.0.1/bin/kramdoc:5:in `<top (required)>'
	from /home/vt/.local/share/gem/ruby/3.0.0/bin/kramdoc:23:in `load'
	from /home/vt/.local/share/gem/ruby/3.0.0/bin/kramdoc:23:in `<main>'
```
The tests fail on  `Kramdown::Parser::Html::ElementConverter`.

- ruby 3.0.1p64 (2021-04-05 revision 0fb782ee38) [x86_64-linux]
- gem 3.2.15
- Bundler version 2.2.16

**Comment by mojavelinux** [comment]
Ruby 3.0 pulled rexml from stdlib, which means we now have to declare it as a dependency. I'll go ahead and make the update.
